export const AnimalsData = [
  {
    name: 'Estrela',
    race: 'Mustang',
    coat: 'Castanha',
    registerNumber: '3265371',
    property: '',
    sex: 'female',
    photo: 'https://source.unsplash.com/random/200x200/?horse',
    function: '',
    register: true,
    sale: '',
    value: '',
    registerDate: '',
    birthDate: '',
    father: '',
    mother: '',
  },
  {
    name: 'Zé',
    race: 'Mustang',
    coat: 'Rajado',
    registerNumber: '0743223',
    property: '',
    sex: 'male',
    photo: 'https://source.unsplash.com/random/200x200/?horse',
    function: '',
    register: true,
    sale: '',
    value: '',
    registerDate: '',
    birthDate: '',
    father: '',
    mother: '',
  },
  {
    name: 'Est tristique',
    race: 'Mustang',
    coat: 'Branca',
    registerNumber: undefined,
    property: '',
    sex: 'male',
    photo: 'https://source.unsplash.com/random/200x200/?horse',
    function: '',
    register: false,
    sale: '',
    value: '',
    registerDate: '',
    birthDate: '',
    father: '',
    mother: '',
  },
  {
    name: 'Parturient vel',
    race: 'Mustang',
    coat: 'Castanha',
    registerNumber: '8569128',
    property: '',
    sex: 'female',
    photo: 'https://source.unsplash.com/random/200x200/?horse',
    function: '',
    register: true,
    sale: '',
    value: '',
    registerDate: '',
    birthDate: '',
    father: '',
    mother: '',
  },

  {
    name: 'Spirit',
    race: 'Mustang',
    coat: 'Castanha',
    registerNumber: 'B9873131',
    property: '',
    sex: 'male',
    photo: 'https://source.unsplash.com/random/200x200/?horse',
    function: '',
    register: true,
    sale: '',
    value: '',
    registerDate: '',
    birthDate: '',
    father: '',
    mother: '',
  },
];
