export const AdminData = [
  {
    name: 'Jorge Penteado',
    email: 'Test@test1.com',
    cpf: '00000000000',
    phone: '09123456789',
    role: 'Perfil Personalizado',
    status: 'Ativo',
    photo: 'https://avatars.githubusercontent.com/u/116733347?v=4',
  },
  {
    name: 'Elísio Ávila',
    email: 'Test@test2.com',
    cpf: '00000000000',
    phone: '09123456789',
    role: 'Acesso completo',
    status: 'Ativo',
    photo: 'https://avatars.githubusercontent.com/u/116733347?v=4',
  },
  {
    name: 'Ivone Arruda',
    email: 'Test@test3.com',
    cpf: '00000000000',
    phone: '09123456789',
    role: 'Cuidador(a)',
    status: 'Inativo',
    photo: 'https://avatars.githubusercontent.com/u/116733347?v=4',
  },
  {
    name: 'fulanodetal@gmail.com',
    email: 'Test@test4.com',
    cpf: '00000000000',
    phone: '09123456789',
    role: 'Financeiro',
    status: 'Pendente',
    photo: 'https://avatars.githubusercontent.com/u/116733347?v=4',
  },
];

export const functions = [
  {
    name: 'CADASTRO',
    allView: false,
    allEdit: false,
    allDelete: false,
    haveItem: {
      view: false,
      edit: false,
      delete: false,
    },
    props: [
      {name: 'Clientes', view: false, edit: false, delete: false},
      {name: 'Fornecedores', view: false, edit: false, delete: false},
      {name: 'Alteração de Planos', view: false, edit: false, delete: false},
      {name: 'Animal', view: false, edit: false, delete: false},
      {name: 'Propriedade', view: false, edit: false, delete: false},
    ],
  },
  {
    name: 'REPRODUTIVO',
    allView: false,
    allEdit: false,
    allDelete: false,
    haveItem: {
      view: false,
      edit: false,
      delete: false,
    },
    props: [
      {name: 'Genealogia', view: false, edit: false, delete: false},
      {name: 'Inseminação', view: false, edit: false, delete: false},
      {name: 'Prenhes Positiva', view: false, edit: false, delete: false},
    ],
  },
  {
    name: 'CLÍNICO',
    allView: false,
    allEdit: false,
    allDelete: false,
    haveItem: {
      view: false,
      edit: false,
      delete: false,
    },
    props: [
      {name: 'Manejo nutricional', view: false, edit: false, delete: false},
      {name: 'Vermifugação', view: false, edit: false, delete: false},
      {name: 'Vacinas', view: false, edit: false, delete: false},
      {name: 'Procedim. veterinários', view: false, edit: false, delete: false},
      {name: 'Ferregeamento', view: false, edit: false, delete: false},
      {name: 'Exames', view: false, edit: false, delete: false},
    ],
  },
  {
    name: 'ACOMPANHAMENTO',
    allView: false,
    allEdit: false,
    allDelete: false,
    haveItem: {
      view: false,
      edit: false,
      delete: false,
    },
    props: [
      {name: 'Marcações', view: false, edit: false, delete: false},
      {name: 'Grafico de medidas', view: false, edit: false, delete: false},
    ],
  },
  {
    name: 'ESPORTE',
    allView: false,
    allEdit: false,
    allDelete: false,
    haveItem: {
      view: false,
      edit: false,
      delete: false,
    },
    props: [
      {name: 'Evento', view: false, edit: false, delete: false},
      {name: 'Competições', view: false, edit: false, delete: false},
      {name: 'Vincular animal', view: false, edit: false, delete: false},
    ],
  },
  {
    name: 'COMERCIAL',
    allView: false,
    allEdit: false,
    allDelete: false,
    haveItem: {
      view: false,
      edit: false,
      delete: false,
    },
    props: [
      {name: 'Contatos', view: false, edit: false, delete: false},
      {name: 'Vendas', view: false, edit: false, delete: false},
      {name: 'Orçamentos', view: false, edit: false, delete: false},
      {name: 'Notas fiscais', view: false, edit: false, delete: false},
      {name: 'Recibos', view: false, edit: false, delete: false},
      {name: 'Ordens de serviço', view: false, edit: false, delete: false},
      {name: 'Produtos', view: false, edit: false, delete: false},
      {name: 'Estoque', view: false, edit: false, delete: false},
      {name: 'Inventario', view: false, edit: false, delete: false},
    ],
  },
  {
    name: 'COMPRAS',
    allView: false,
    allEdit: false,
    allDelete: false,
    haveItem: {
      view: false,
      edit: false,
      delete: false,
    },
    props: [
      {name: 'Itens de compras', view: false, edit: false, delete: false},
      {name: 'Orçamentos', view: false, edit: false, delete: false},
      {name: 'Parcelas a pagar', view: false, edit: false, delete: false},
      {
        name: 'Gestão de Notas Fiscais',
        view: false,
        edit: false,
        delete: false,
      },
      {name: 'Estoque', view: false, edit: false, delete: false},
    ],
  },
  {
    name: 'FINANCEIRO',
    allView: false,
    allEdit: false,
    allDelete: false,
    haveItem: {
      view: false,
      edit: false,
      delete: false,
    },
    props: [
      {name: 'Valores do caixa', view: false, edit: false, delete: false},
      {name: 'Gráficos', view: false, edit: false, delete: false},
    ],
  },
];
